const PARSE_APP_ID = process.env.PARSE_APP_ID;
const PARSE_JAVASCRIPT_KEY = process.env.PARSE_JAVASCRIPT_KEY;

module.exports = {
  PARSE_APP_ID: "XAtVPxiVwwoH9fMBcOjCkVZYoaCV66jTbeRTQC7e",
  PARSE_JAVASCRIPT_KEY: "6SPRaK3IH8GDJePVjgdeuXEFpcvUcSTrEdMPsnf2",
};
